name: Create and Merge PR

on: push

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.GH_APP_ID }}
        application_private_key: ${{ secrets.GH_APP_KEY }}
    
    - name: Create Pull Request
      run: |
        echo "Creating Pull Request..."
        curl -X POST -H "Authorization: token ${{ steps.get_workflow_token.outputs.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/goushaa/gold/pulls -d '{"title":"Merge common-workflows master into gold master","head":"common-workflows-master","base":"master"}'
