name: Create and Merge PR

on: push

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.GH_APP_ID }}
        application_private_key: ${{ secrets.GH_APP_KEY }}
    
    - name: Create Pull Request
      run: |
        echo "Creating Pull Request..."
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.get_workflow_token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/goushaa/gold/pulls \
          -d '{"title":"Automated PR","body":"This is an automated pull request.","head":"common-workflows:main","base":"main"}' \
          | tee pr_output.json