name: Create and Merge PR

on: push

#

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.GH_APP_ID }}
        application_private_key: ${{ secrets.GH_APP_KEY }}    
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: goushaa/gold
        token: ${{ steps.get_workflow_token.outputs.token }}

    - name: Generate random number
      id: random
      run: echo "::set-output name=value::$(echo $RANDOM)"

    - name: create branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      with:
        branch: post-${{ steps.random.outputs.value }}
        token: ${{ steps.get_workflow_token.outputs.token }}

    - name: download file
      run: wget ${{ github.event.issue.body }} -O source/_posts/
      
    - name: commit and push new file
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit -m "New post"
        git push -u origin post-${{ steps.random.outputs.value }}  

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.get_workflow_token.outputs.token }}
        title: 'title'
        body: 'description'
        branch: 'post-${{ steps.random.outputs.value }} '
        base: 'main'
        draft: false      