name: Create and Merge PR

on: push

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from common-workflows
      uses: actions/checkout@v3  

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.GH_APP_ID }}
        application_private_key: ${{ secrets.GH_APP_KEY }}    
    
    - name: Checkout gold repository
      uses: actions/checkout@v3 
      with:
        repository: goushaa/gold
        token: ${{ steps.get_workflow_token.outputs.token }}
        ref: main  

    - name: Generate random number
      id: random
      run: echo "value=$RANDOM" >> $GITHUB_ENV 

    - name: Create new branch
      uses: peterjgrainger/action-create-branch@v2.1.0  
      env:
        GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      with:
        branch: post-${{ env.value }}  

    - name: Create file with random number in the root directory
      run: echo "${{ env.value }}" > random_number.txt  
      
    - name: Commit and push new file
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "ahmed.bassem2002@gmail.com"
        git add .
        git commit -m "New post with random number"
        git push -u origin post-${{ env.value }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.get_workflow_token.outputs.token }}
        title: 'New post with random number'
        body: 'This PR contains a new post with a random number.'
        head: post-${{ env.value }}
        base: 'main'
        draft: false
