name: Create and Merge PR

on: push

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.GH_APP_ID }}
        application_private_key: ${{ secrets.GH_APP_KEY }}    
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: goushaa/gold
        token: ${{ steps.get_workflow_token.outputs.token }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.get_workflow_token.outputs.token }}
        title: 'title'
        body: 'description'
        branch: 'kady-PR'
        base: 'main'
        draft: false      